<?php
/**
 * Plugin Name:  Headless Woo Return Redirect
 * Plugin URI:   https://github.com/your-repo/headless-woo
 * Description:  Redirects WooCommerce payment return URLs to the headless Next.js storefront.
 *               After a customer pays (success, failure, or cancellation), WooCommerce will
 *               send them back to /order/verify on the Next.js frontend instead of the
 *               default WooCommerce thank-you page.
 * Version:      1.0.0
 * Requires at least: 5.8
 * Requires PHP:  7.4
 * Author:        Your Team
 * License:       GPL-2.0-or-later
 *
 * ── INSTALLATION ──────────────────────────────────────────────────────────────
 * 1. Upload this file to:
 *      /wp-content/plugins/headless-woo-return-redirect/headless-woo-return-redirect.php
 *    (Create the directory if it does not exist.)
 * 2. Log in to the WordPress Admin → Plugins → Activate "Headless Woo Return Redirect".
 * 3. Edit the HWRR_FRONTEND_URL constant below to match your Next.js domain.
 *    Alternatively, define it in wp-config.php BEFORE activating the plugin:
 *      define( 'HWRR_FRONTEND_URL', 'https://your-nextjs-domain.replit.app' );
 * 4. Done. WooCommerce will now redirect customers to your Next.js /order/verify page.
 *
 * ── HOW IT WORKS ──────────────────────────────────────────────────────────────
 * WooCommerce has two hooks that determine where the customer lands after payment:
 *
 *   woocommerce_get_return_url  — primary hook used by most gateways
 *   woocommerce_order_received_url — fallback used by some gateways / COD
 *
 * This plugin overrides both to produce:
 *   {HWRR_FRONTEND_URL}/order/verify?order_id={id}&key={order_key}
 *
 * The Next.js /order/verify page then:
 *   1. Reads order_id and key from the query string.
 *   2. Calls the WooCommerce REST API server-side to fetch the real order status.
 *   3. Compares the provided key with order.order_key (prevents forgery).
 *   4. Displays success / pending / failed / cancelled UI accordingly.
 *   5. Clears the customer's cart only when status is processing or completed.
 *
 * ── SECURITY NOTES ────────────────────────────────────────────────────────────
 * • order_key is an unguessable random token generated by WooCommerce.
 *   Knowing the order_id alone is NOT enough to access order data — the key must match.
 * • The Next.js page verifies the key server-side via the WooCommerce REST API.
 * • WooCommerce credentials (consumer key/secret) never leave the server.
 * • URLs are sanitized with esc_url_raw() before use.
 * • Only frontend checkout returns are affected. Admin order pages are untouched.
 *
 * ── GATEWAY COMPATIBILITY ─────────────────────────────────────────────────────
 * Tested with: COD, Stripe for WooCommerce, PayPal Payments, PayFort, Moyasar.
 * For gateways that use custom redirect logic and bypass these filters, you may
 * also need to configure the gateway's "Return URL" field in its settings to:
 *   {HWRR_FRONTEND_URL}/order/verify?order_id={order_id}&key={order_key}
 * Some gateways (e.g. Stripe) support {ORDER_ID} and {ORDER_KEY} placeholders.
 */

defined( 'ABSPATH' ) || exit;

// ── Configuration ─────────────────────────────────────────────────────────────
// Override this in wp-config.php to avoid editing the plugin file directly.
if ( ! defined( 'HWRR_FRONTEND_URL' ) ) {
	define( 'HWRR_FRONTEND_URL', 'https://your-nextjs-domain.replit.app' );
}

// ── Hook: primary return URL ───────────────────────────────────────────────────

/**
 * Override the WooCommerce order return URL.
 *
 * @param string   $return_url The default WooCommerce return URL.
 * @param WC_Order $order      The WooCommerce order object.
 * @return string  The new URL pointing to the Next.js storefront.
 */
add_filter( 'woocommerce_get_return_url', 'hwrr_override_return_url', 10, 2 );

function hwrr_override_return_url( $return_url, $order ) {
	if ( ! $order instanceof WC_Order ) {
		return $return_url;
	}

	return hwrr_build_verify_url( $order );
}

// ── Hook: order-received (thank-you) URL ──────────────────────────────────────

/**
 * Override the WooCommerce order-received / thank-you page URL.
 * Some gateways use this hook instead of woocommerce_get_return_url.
 *
 * @param string   $url   The default order-received URL.
 * @param WC_Order $order The WooCommerce order object.
 * @return string  The new URL pointing to the Next.js storefront.
 */
add_filter( 'woocommerce_order_received_url', 'hwrr_override_received_url', 10, 2 );

function hwrr_override_received_url( $url, $order ) {
	if ( ! $order instanceof WC_Order ) {
		return $url;
	}

	return hwrr_build_verify_url( $order );
}

// ── Helper ────────────────────────────────────────────────────────────────────

/**
 * Build the Next.js /order/verify URL for a given order.
 *
 * @param  WC_Order $order
 * @return string   Sanitized absolute URL.
 */
function hwrr_build_verify_url( WC_Order $order ): string {
	$frontend_url = rtrim( HWRR_FRONTEND_URL, '/' );
	$order_id     = absint( $order->get_id() );
	$order_key    = sanitize_text_field( $order->get_order_key() );

	// add_query_arg handles proper URL encoding of values.
	$verify_url = add_query_arg(
		array(
			'order_id' => $order_id,
			'key'      => $order_key,
		),
		$frontend_url . '/order/verify'
	);

	return esc_url_raw( $verify_url );
}
